# 配置参考 https://segmentfault.com/a/1190000020340570
version: '3.8'
services:

  # 前端服务
  lumena:
    container_name: lumena
    build: .
    restart: always
    ports:
      - "8080:80"
    networks:
      - matrix-network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.lumena.rule=Host(`meteor.matrix-net.tech`)"
      - "traefik.http.routers.lumena.service=lumena"
      - "traefik.http.services.lumena.loadbalancer.server.port=80"

networks:
  matrix-network:
    driver: bridge
    name: matrix-network
